version: '3.3'
services:
  nginx:
    image: nginx:latest
    container_name: site-nginx
    ports:
      - 127.0.0.1:8181:80
    volumes:
      - ./project:/app
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/logs:/var/log/nginx/
  php:
    build:
      dockerfile: Dockerfile
      context: 'docker'
      args:
        PHP_USER_ID: 1000
        PHP_USER_NAME: site-user
    container_name: site-php
    env_file:
      - .env
    volumes:
      - ./project:/app
  db:
    image: percona:ps-8.0
    container_name: site-mysql
    env_file:
      - .env
    ports:
      - 3306:3306
    cap_add:
      - SYS_NICE
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql_dump/:/mysql_dump/:rw
    restart: unless-stopped
  adminer:
    image: adminer
    restart: always
    ports:
      - 127.0.0.1:8281:8080
volumes:
  mysql-data:
